LATEXMK = latexmk -bibtex -pdf -outdir=_build -auxdir=_build
LATEXMK_WATCH = $(LATEXMK) -pvc -interaction=nonstopmode

SOURCES=$(shell find . -name '*.tex' -or -name '*.bib' -or -name '*.sty' -or -name '*.cfg' | grep -v toplas-diff.tex)

BUILD=_build

%.log: %.pdf
	@cat $(BUILD)/$@

%.wlog: %.pdf
	@$(MAKE) $*.log | grep -E '(Warning:|pdfTeX warning|Overfull)'

%.werr: %.pdf
	@$(MAKE) $*.wlog | grep -v -f warnings.ok

%.ok: %.pdf Makefile
	if $(MAKE) $*.werr | grep -v Font | grep -i 'warning'; then false; fi
	touch $@

.PRECIOUS: %.pdf

%.pdf: %.tex ${SOURCES}
	@mkdir -p $(BUILD)
	$(LATEXMK) $* || (cp $(BUILD)/$@ . && false)
	cp $(BUILD)/$@ .

%.wpdf: %.tex ${SOURCES}
	$(LATEXMK_WATCH) $<

%.view: %.pdf
	open $< &
