open! Import

(** [infer_exp exp] returns the constraint generated by [exists 'a. [| exp : 'a |]]. *)
val infer_exp
  :  ?with_stdlib:bool
  -> with_poly_params:bool
  -> Ast.expression
  -> unit Constraint.t

(** [infer_str str] returns the constraint generated by [[| str |]] *)
val infer_str
  :  ?with_stdlib:bool
  -> with_poly_params:bool
  -> Ast.structure
  -> Typed_ast.signature Constraint.t

(** [check cst] checks that [cst] is satisfiable and returns its semantic value.

    @raises Omniml_error.T if the constraint is unsatisfiable *)
val check
  :  with_poly_params:bool
  -> ?defaulting:Omniml_options.Defaulting.t
  -> ?range:Range.t
  -> 'a Constraint.t
  -> 'a
