open! Import

(** [infer_exp exp] returns the constraint generated by [exists 'a. [| exp : 'a |]]. *)
val infer_exp : ?with_stdlib:bool -> Ast.expression -> Constraint.t

(** [infer_str str] returns the constraint generated by [[| str |]] *)
val infer_str : ?with_stdlib:bool -> Ast.structure -> Constraint.t

(** [check cst] checks that [cst] is satisfiable 

    @raises Omniml_error.T if the constraint is unsatisfiable *)
val check
  :  ?defaulting:Omniml_options.Defaulting.t
  -> ?range:Range.t
  -> Constraint.t
  -> unit
